### PR TITLE
Idsite multitenant integration

### PR DESCRIPTION
**Pull request by dogeared**
Github is saying it can't automatically merge, but when I merged `idsite-multitenant-integration` into `spring_security_extension` locally, there were no conflicts.

### CODE REVIEW

**Comment by lhazlewood** [comment]
We should probably start squashing commits for PRs so there is only one change set

**Comment by lhazlewood** [comment]
e.g. http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by lhazlewood** [comment]
I think this is why Travis is saying we can't merge: https://travis-ci.org/stormpath/stormpath-sdk-java/builds/83526197

**Comment by dogeared** [comment]
Right.

```
Caused by: org.springframework.expression.ParseException: Expression '#{ @environment['stormpath.web.idSite.showOrganizationField] }' @ 16: Found non terminating string literal starting at position 16
```

That was the commit with the missing single quote. Let me push up a squashed version and see if that gets rid of it.

**Comment by dogeared** [comment]
I think it's complaining because the idsite-multitenant-integration branch was cut from master and we now want to merge it in to spring_security_extension?

FWIW, github was still complaining about a squashed version of the idsite-multitenant-integration branch being merged into spring_security_extension.

I could just merge idsite-multitenant-integration into spring_security_extension locally (which has no merge conflicts), make sure all the tests run and push it up.

Or we could merge idsite-multitenant-integration into master

Thoughts?

**Comment by lhazlewood** [comment]
I'd merge to master and then merge master into the spring branch (because the change isn't spring specific)

**Pull request closed without merging**
