### PR TITLE
JSON Form model displays label and placeHolder fields as i18n keys

### LINKED ISSUE #652: JSON Form model displays label and placeHolder fields as i18n keys
Need to resolve the property if the response is JSON, for HTML this is done in the actual view.

This code is not yet in master only in 364-spa-support-merged, that's why the ticket is **blocked**

```
⇒  curl -v -s -H "Accept: application/json" http://localhost:8080/register | jq
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /register HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.48.0
> Accept: application/json
> 
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Wed, 25 May 2016 16:48:28 GMT
< 
{ [1786 bytes data]
* Connection #0 to host localhost left intact
{
  "form": {
    "fields": [
      {
        "name": "givenName",
        "label": "stormpath.web.register.form.fields.givenName.label",
        "placeholder": "stormpath.web.register.form.fields.givenName.placeholder",
        "required": true,
        "type": "text"
      },
      {
        "name": "surname",
        "label": "stormpath.web.register.form.fields.surname.label",
        "placeholder": "stormpath.web.register.form.fields.surname.placeholder",
        "required": true,
        "type": "text"
      },
      {
        "name": "email",
        "label": "stormpath.web.register.form.fields.email.label",
        "placeholder": "stormpath.web.register.form.fields.email.placeholder",
        "required": true,
        "type": "email"
      },
      {
        "name": "password",
        "label": "stormpath.web.register.form.fields.password.label",
        "placeholder": "stormpath.web.register.form.fields.password.placeholder",
        "required": true,
        "type": "password"
      }
    ]
  },
  "accountStores": [
    {
      "href": "https://api.stormpath.com/v1/directories/c3Rwcf17S95IMsG6MTvGq",
      "provider": {
        "href": "https://api.stormpath.com/v1/directories/c3Rwcf17S95IMsG6MTvGq/provider",
        "providerId": "google",
        "clientId": "584731295650-uh34m1td8ck396q3rebtlb5tspevrcea.apps.googleusercontent.com"
      },
      "name": "google"
    },
    {
      "href": "https://api.stormpath.com/v1/directories/1rdrV2qwHnHrxhIuPwmTaa",
      "provider": {
        "href": "https://api.stormpath.com/v1/directories/1rdrV2qwHnHrxhIuPwmTaa/provider",
        "providerId": "facebook",
        "clientId": "1097146426990640"
      },
      "name": "facebook"
    },
    {
      "href": "https://api.stormpath.com/v1/directories/7OGqZDE5BhANboyyqPsb5c",
      "provider": {
        "href": "https://api.stormpath.com/v1/directories/7OGqZDE5BhANboyyqPsb5c/provider",
        "providerId": "github",
        "clientId": "70fc585effbf54ea771c"
      },
      "name": "github"
    },
    {
      "href": "https://api.stormpath.com/v1/directories/2gDG34Hnus377zEc2U7tGC",
      "provider": {
        "href": "https://api.stormpath.com/v1/directories/2gDG34Hnus377zEc2U7tGC/provider",
        "providerId": "linkedin",
        "clientId": "776ge4vrjonhcx"
      },
      "name": "linkedin"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by jarias**
Fixes #652

### CODE REVIEW

**Comment by mrioan** [comment]
This PR is blocked on #663 since it is executions `(isJsonPreferred(request))` but that is actually not accurate with the Content Negotiation strategy

**Comment by mrioan** [comment]
@jarias I think you can get back to this issue as the Content Negotiation code is already available in `364-spa-support-merged` The code on this PR should to be doing `isJsonPreferred(request)` but using the `ContentNegotiationResolver` instead. Back to you. Thanks!

**Comment by lhazlewood** [comment]
If we have a `ContentNegotiationResolver` concept, I think this might be incorrectly named.  It wouldn't resolve a `ContentNegotiation` - it would resolve a content type, correct?

If so, that would imply it should be named a `ContentTypeResolver` or `AcceptTypeResolver` that _uses_ content negotiation to get its work done.

The current project convention is to name `Resolver` types based on the thing that is resolved, not the algorithm used during resolution.

**Comment by mraible** [comment]
I believe the evil #666 fixes this. 💀

**Pull request closed without merging**
