### PR TITLE
Updated example and tutorial poms to be included in deployment

### LINKED ISSUE #724: Publish example and tutorial jars

### PR DESCRIPTION
**Pull request by dogeared**
Resolves #724

### CODE REVIEW

**Comment by mrioan** [comment]
LGTM. Merge please. Thanks! @dogeared

**Comment by dogeared** [comment]
Thanks @mrioan. One question: The root of `examples` and `tutorials` still has `<skip>true</skip>` will this cause the sub-projects to be skipped? If so, I'll need to update the parent poms as well.

**Comment by mraible** [comment]
@dogeared Yes, this should cause the sub-projects will be skipped. However, even if you change `examples/pom.xml` to remove `<skip>true</skip>`, most of the sub-projects override it, so just changing the parent won't work.

* examples/spring
* examples/spring-boot
* examples/spring-boot-default
* examples/spring-boot-webmvc
* examples/spring-security-spring-boot-webmvc
* examples/spring-security-spring-boot-webmvc-bare-bones
* examples/spring-security-webmvc
* examples/spring-webmvc

Also, we should change `<jdk.version>1.6</jdk.version>` to `<jdk.version>1.7</jdk.version>` in all the examples.

**Comment by dogeared** [comment]
Right, @mraible - this PR updates all the sub-projects. I will update the root for each of them as well as the java version. Thanks.

**Comment by dogeared** [comment]
@mrioan and/or @mraible - please take another look. I've update jdk version and parent poms for examples and tutorials.

**Comment by mraible** [comment]
LGTM 👍

**Pull request merged**
