### PR TITLE
issue 1049 - added expand resolver to MeController, and corresponding…

### LINKED ISSUE #1049: Add Expand Options Resolver to MeController

### PR DESCRIPTION
**Pull request by iancorcoran**
resolves #1049

### CODE REVIEW

**Comment by mraible** [comment]
What is the purpose of this change? Is it related to https://github.com/stormpath/stormpath-sdk-java/issues/1044 at all?

**Comment by dogeared** [comment]
Hey @iancorcoran - I think a test would be helpful in understanding the purpose of this change. Back to you! Thanks.

**Comment by iancorcoran** [comment]
@mraible As the SDK stands right now, the expand options are read on startup and are fixed from that point. We have an internal use case where it would be useful to supply different expand options on a request by request basis (hit me up on slack if you'd like more info on that). It is not related to #1044 

@dogeared Existing test coverage should be sufficient to exercise the added code but I can add another. Thanks.

**Comment by iancorcoran** [comment]
@mraible @dogeared Test added, let me know if you any other questions...

**Comment by mraible** [comment]
LGTM 👍  pending CI passing.

**Pull request merged**
