### PR TITLE
Add the saveWithResponseOptions(Options) operation to the Resources missing it (JSDK-201)

### PR DESCRIPTION
**Pull request by maranai**

### CODE REVIEW

**Comment by mrioan** [comment]
@maranai I approve this PR. Thanks!

**Comment by lhazlewood** [comment]
@maranai @mrioan please ensure all builds pass before merging to master.

**Comment by maranai** [comment]
Tests not passing were fixed. There's a test not passing in MinimalStormpathConfigurationIT class that has randomly failed in the past.

**Comment by mrioan** [comment]
Solves #95

**Pull request merged**
