### PR TITLE
Updated code to reflect changes that breaks the use of SAML with ID Site.

### LINKED ISSUE #554: Update IDSiteCallbackHandler for be in sync with backend
There was a change in the backend that removes the aud claim in the payload and relies on kid in the header.

For Stormpath internal: AM-3024 introduced this change.

### PR DESCRIPTION
**Pull request by dogeared**
Resolves #554 

Namely, looking for kid in header and not requiring aud claim in payload. Updated tests to shift aud claim in payload to kid claim in header.

### CODE REVIEW

**Comment by jarias** [comment]
LGTM except fo the travis CI build.

**Comment by lhazlewood** [comment]
LGTM - please merge!

**Comment by lhazlewood** [comment]
@dogeared delete the branch?

**Comment by dogeared** [comment]
done

**Pull request merged**
