### PR TITLE
Coverage clover

### LINKED ISSUE #431: Integrate code coverage plugin for unit and integration tests
Jacoco? I say: Yes

Cobertura is not actively maintained.

IntelliJ supports using Jacoco as its coverage tool so command line will match IntelliJ

Need to determine baseline: What % coverage satisfies this ticket to start with? That should be enforced in the pom.xml.

### PR DESCRIPTION
**Pull request by dogeared**
resolves #431 

NOTE: I had difficulty in getting the single-module approach to clover working. I believe there is a bug whereby it cannot deal with modules nested more than one level deep.

When I followed the instructions here and here, I kept ending up with the same error result:

```
[ERROR] Failed to execute goal com.atlassian.maven.plugins:clover-maven-plugin:4.1.1:aggregate (main) on project stormpath-spring-parent: Clover has failed to merge the children module databases -> [Help 2]
[ERROR] Failed to execute goal com.atlassian.maven.plugins:clover-maven-plugin:4.1.1:aggregate (main) on project stormpath-spring-boot-parent: Execution main of goal com.atlassian.maven.plugins:clover-maven-plugin:4.1.1:aggregate failed: String index out of range: -5 -> [Help 3]
[ERROR] Failed to execute goal com.atlassian.maven.plugins:clover-maven-plugin:4.1.1:aggregate (main) on project stormpath-sdk-tutorials-spring-boot: Execution main of goal com.atlassian.maven.plugins:clover-maven-plugin:4.1.1:aggregate failed: String index out of range: -4 -> [Help 3]
```

While the approach in this PR requires the (empty) `clover` module, it works and it is setup in such a way that the clover coverage tests are only run with the `clover.all` profile.

I've noted in the pom that we are using the older approach and we will open a ticket with Atlassian to address the issue.

### CODE REVIEW

**Comment by dogeared** [comment]
NOTE: While we cannot (easily) save historical data on travis, I did confirm that the build will fail on travis if the coverage dips below the specified threshold, currently 60%:

```
[INFO] Stormpath Java :: CLOVER ........................... FAILURE [ 31.095 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:05 min
[INFO] Finished at: 2016-03-10T14:55:20+00:00
[INFO] Final Memory: 296M/479M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.atlassian.maven.plugins:clover-maven-plugin:4.1.1:check (clover.everything) on project stormpath-clover: Build failed to meet Clover coverage targets: The following coverage targets for null were not met:
[ERROR] Total coverage of 60.1% did not meet target of 90%
```

**Comment by jarias** [comment]
LGTM @dogeared

**Comment by dogeared** [comment]
@jarias - would you take one more look? I added some script code to publish the results to a heroku instance so that we can all browse the results even if we are not all running clover locally.

**Comment by jarias** [comment]
LGTM @dogeared

**Pull request merged**
