### PR TITLE
Added getExpandedJwt() to Access and Refresh Tokens

### PR DESCRIPTION
**Pull request by mrioan**

### CODE REVIEW

**Comment by mrioan** [comment]
I am missing ITs, I need to close PR until I add them

**Comment by lhazlewood** [comment]
Why was this closed entirely?  Won't the PR still be merged later?  It is odd in git workflows to close a PR when it will still be merged in the future, which is exactly why GitHub is warning us via its message:

> This pull request is closed, but the expose_expandedJwt_in_tokens branch has unmerged commits.

**Comment by mrioan** [comment]
@lhaslewood I closed it with a comment. I created the PR but I had forgotten to add ITs so the code was not ready and de do not want to hace PRs that actually are not really ready to be reviewed. Makes sense?

**Comment by lhazlewood** [comment]
Got it - thanks!

**Pull request closed without merging**
