### PR TITLE
IDSite error callback

### PR DESCRIPTION
**Pull request by mrioan**

### CODE REVIEW

**Comment by mrioan** [comment]
NOTE: DO NOT merge until this code can be validated against staging.

**Comment by maranai** [comment]
@mrioan now that this feature is available in production please check if it's possible to add an IT for this. Might not be possible though.

**Comment by maranai** [comment]
@mrioan this PR is approved. I've verified it is according to the specification. I updated the versions to match 1.0.RC5

**Comment by dogeared** [comment]
resolved #261

**Pull request merged**
