### PR TITLE
Added in JSP templates in permit all list for use with Spring Security WebMVC.

### LINKED ISSUE #822: Spring Security: "sanctioned" paths return `302` when using `Accept:text/html`
Steps to Reproduce:

1. Start the Spring Security WebMVC example
2. confirm that `Accept:application/json` is working properly: 
    * `http localhost:8080/login Accept:application/json`
    * **returns**: json login model as expected
3. confirm that `Accept:text/html` is not working properly:
    * `http localhost:8080/login Accept:text/html`
    * **returns**: 302 with Location header *back* to /login AND incorrectly sets the `WWW-Authenticate` header

### LINKED ISSUE #823: `next` param replication
In the `Spring Security WebMVC Example`, when you hit an endpoint that requires auth, it redirects to `/login`. This is correct. However, the `next` param keeps getting appended to each subsequent `Location` header value.

Steps to reproduce:

1. curl -v -H "Accept: text/html" http://localhost:8080/missing
    * **returns**: 302, `Location: /login?next=%2Fmissing`
1. curl -v -H "Accept: text/html" http://localhost:8080/missing
    * **returns**: 302, `Location: /login?next=%2Fmissing?next=%2Fmissing`
1. curl -v -H "Accept: text/html" http://localhost:8080/missing
    * **returns**: 302, `Location: /login?next=%2Fmissing?next=%2Fmissing?next=%2Fmissing`

### PR DESCRIPTION
**Pull request by dogeared**
Fixes #822

### CODE REVIEW

**Comment by dogeared** [comment]
per conversation with @lhazlewood, this needs more work. This is a workaround that shows that Spring Security is intercepting the final forward to `/WEB-INF/jsp/stormpath/login.jsp` (for instance). We need to find the right spot to prevent this behavior. @mrioan - take a look if you have a chance in the morning.

**Comment by dogeared** [comment]
Another note:

Eventually, we are getting to (Spring's) `InternalResourceView.render` from Stormpath's `SpringView`.

It's (properly) determining the `dispatcherPath` as: `/WEB-INF/jsp/stormpath/login.jsp`, but when `rd.forward(request, response);` is called, Spring Security is intercepting it. It should *not* be at this point.

**Comment by dogeared** [comment]
Further:

This was recently added to `AbstractStormpathWebMvcConfiguration`:

```
    public InternalResourceViewResolver stormpathJspViewResolver() {
        InternalResourceViewResolver bean = new InternalResourceViewResolver();
        bean.setOrder(jspViewResolverOrder);
        bean.setViewClass(JstlView.class);
        bean.setPrefix("/WEB-INF/jsp/");
        bean.setSuffix(".jsp");
        return bean;
    }
```

It may be that we need to tell Spring Security to allow these paths. Here's an older reference to something like this: http://stackoverflow.com/questions/2010475/infinite-loop-using-spring-security-login-page-is-protected-even-though-it-sho

**Comment by mraible** [comment]
@dogeared I pulled this branch to test and login seems to render just fine. However, I did notice that http://localhost:8080/foo returns a 404 as JSON.

```
{
    status: "error.pageNotFound",
    message: "No handler found for GET /foo",
    fieldErrors: null
}
```

**Comment by dogeared** [comment]
per conversation with @mrioan, this PR now lets any `/WEB-INF/jsp/stormpath/` path through spring security. We can resolve the underlying issue without breaking changes post 1.0 release

**Comment by dogeared** [comment]
@mraible - With no accept header, I get JSON back as well, but it's a `401`, which is what it should be. Were you running the Spring Security WebMVC example?

If I do:

`http localhost:8080/blarg`

I get:

```
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Length: 118
Content-Type: application/json
Date: Mon, 01 Aug 2016 15:54:33 GMT
Expires: 0
Pragma: no-cache
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=802E542160B5417FA0E9656533915EAF; Path=/; HttpOnly
WWW-Authenticate: Bearer realm="My Application"
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block

{
    "fieldErrors": null,
    "message": "Full authentication is required to access this resource",
    "status": "error.accessDenied"
}
```

If I do:

`http localhost:8080/blarg Accept:text/html`

I get:

```
HTTP/1.1 302 Found
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Length: 0
Date: Mon, 01 Aug 2016 15:56:39 GMT
Expires: 0
Location: http://localhost:8080/login?next=%2Fblarg
Pragma: no-cache
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=77017EFBEC6790333FBC1166ADBF21F1; Path=/; HttpOnly
WWW-Authenticate: Bearer realm="My Application"
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
```

which is also correct.

**Comment by mraible** [comment]
@dogeared I was just using my browser and running `spring-webmvc`.

image

I created #828 to track this issue.

**Pull request merged**
