### PR TITLE
Coverage clover tck

### LINKED ISSUE #501: Add runtime instrumentation for the code being tested with TCK

### PR DESCRIPTION
**Pull request by mrioan**
This PR causes the `spring-security-webmvc` and `spring-security-spring-boot-webmvc-bare-bones` examples to be run during IT time and get hit by TCK tests.

How to run these TCK tests:

STORMPATH_API_KEY_ID=XXXX STORMPATH_API_KEY_SECRET=YYYY mvn --fail-never -DskipITs=false -Pclover.all clean verify

* XXXX is the apiKeyID of a tenant with no additional apps than the 2 that are always present by default
* YYYY is the apiKeySecret of a tenant with no additional apps than the 2 that are always present by default

In order to run this you need to have `clover.license` under `~/.stormpath/clover/`.

What to check: Any of the Stormpath Jar files inside the `lib` directory of `stormpath-sdk-examples-spring-security-webmvc-1.0.RC9-SNAPSHOT.war` and `stormpath-sdk-examples-spring-security-spring-boot-webmvc-bare-bones-1.0.RC9-SNAPSHOT.jar` must have instrumented code.

BTW, TCK tests will fail as we are not spec complaint yet. We temporarily added `--fail-never` to TCK when it is run

fixes #501

### CODE REVIEW

**Comment by dogeared** [comment]
Hey @mrioan - In master right now, the profile for the clover coverage is: `clover.all`. Would you please update your branch to use this profile? This way we will get the full coverage of the ITs and the TCK.

**Comment by dogeared** [comment]
@mrioan - the `coverage_clover_tck_micah` branch I pushed up has the necessary `clover.all` reference and moves the ITs run to jdk7, which is a requirement for rest assured, fyi. Back to you...

**Comment by mrioan** [comment]
@dogeared thanks for the branch! I pulled it here. You did not mention if it is approved so I am assigning it back to you for a 2nd round of review. Thanks!

**Comment by dogeared** [comment]
LGTM! Pending travis build, merge away!

**Pull request merged**
