### PR TITLE
Add support for client_credentials OAuth grant type

### LINKED ISSUE #569: Add support for client_credentials OAuth grant type
Per the [framework spec](https://github.com/stormpath/stormpath-framework-spec/blob/master/authenticators.md), we need a `OAuthClientCredentialsRequestAuthenticator`

The framework spec also references oauth support [here](https://github.com/stormpath/stormpath-framework-spec/blob/master/oauth2.md).

**Note:** We currently have support for the `client_credentials` `grant_type` in the `BasicAuthenticationScheme`. We need to integrate this functionality into the `/oauth/token` endpoint.

### PR DESCRIPTION
**Pull request by mraible**
This is still very much a work-in-progress. However, I wanted to get some eyeballs on it to see if I'm on the right path. An integration test in `ApplicationIT.groovy` is passing, but I'm not sure I'm doing things correctly or as clean as it could be.

This will eventually fix #569.

### CODE REVIEW

**Comment by mraible** [comment]
Test coverage from looking at the Clover report that @dogeared generated for me:

1. `com.stormpath.sdk.oauth`: 0%
2. `com.stormpath.sdk.impl.oauth`: 71.5%

Classes:

1. `DefaultOAuthClientCredentialsGrantAuthenticationAttempt`: 0%
2. `ClientCredentialsGrantAuthenticationToken`: 75%
3. `DefaultOAuthClientCredentialsGrantRequestAuthenticator`: 94.7%
4. `DefaultOAuthClientCredentialsGrantRequestAuthentication`: 100%
5. `DefaultOAuthClientCredentialsGrantRequestAuthenticationBuilder`: 100%
6. `DefaultOAuthClientCredentialsGrantRequestAuthenticationFactory`: 100%
7. `DefaultOAuthClientCredentialsRequestAuthenticatorFactory`: 100%

**Comment by dogeared** [comment]
Hey @mraible:

I performed the following UAT tests for some of our examples:

1. use `grant_type=client_credentials` to get an `access_token`
    ```
    http -v -f --auth <api key id>:<api key secret> \
        POST localhost:8080/oauth/token \
        Origin:http://localhost:8080 \
        grant_type=client_credentials
    ```

2. use the `access_token` to authenticate

I ignored content negotiation for now as that is in another branch.

**The UAT is currently failing for servlet and Spring Boot. In each of the cases below, I logged in successfully using the regular web login view and using the `grant_type=password` oauth flow to make sure that I was using a valid account.**

Here are the results:

1. `examples/servlet`

    Log shows:

    `09:06:25.880 [http-nio-8080-exec-1] DEBUG c.s.s.s.e.RequestEventListenerAdapter - Received successful authentication request event: com.stormpath.sdk.servlet.authc.impl.DefaultSuccessfulAuthenticationRequestEvent@5d7487fb`

    Response of `grant_type=client_credentials` request:

    ```
    POST /oauth/token HTTP/1.1
    Accept: */*
    Accept-Encoding: gzip, deflate
    Authorization: Basic ...
    Connection: keep-alive
    Content-Length: 29
    Content-Type: application/x-www-form-urlencoded; charset=utf-8
    Host: localhost:8080
    Origin: http://localhost:8080
    User-Agent: HTTPie/0.9.3
    
    grant_type=client_credentials
    
    HTTP/1.1 403 Forbidden
    Content-Language: en
    Content-Length: 1004
    Content-Type: text/html;charset=utf-8
    Date: Thu, 19 May 2016 13:06:25 GMT
    Server: Apache-Coyote/1.1
    ...
    ```

    NOTE: The response was HTML. The default should be JSON with `Accept: */*`. This will likely be taken care of in the content negotiation branch.

2. `examples/spring-security-spring-boot-webmvc-bare-bones`

    Log shows:

    `2016-05-19 09:17:52.999  WARN 6381 --- [nio-8080-exec-6] .f.o.DefaultAccessTokenRequestAuthorizer : The OAuth 2 specification requires secure HTTPS connections during token requests, but the current configuration allows insecure requests.  The Stormpath SDK default configuration allows insecure requests for convenience during localhost development, but CAUTION: it will automatically throw an OAuthException in production instead of logging this warning (where production is defined as !localhost by default). When you deploy your application to staging and production environments, ensure that HTTPS is always enabled otherwise token requests are not likely to function correctly.`

    (We should probably show this in the servlet plugin too)

    Response of `grant_type=client_credentials` request:

    ```
    POST /oauth/token HTTP/1.1
    Accept: */*
    Accept-Encoding: gzip, deflate
    Authorization: Basic ...
    Connection: keep-alive
    Content-Length: 29
    Content-Type: application/x-www-form-urlencoded; charset=utf-8
    Host: localhost:8080
    Origin: http://localhost:8080
    User-Agent: HTTPie/0.9.3
    
    grant_type=client_credentials
    
    HTTP/1.1 403 Forbidden
    Cache-Control: no-cache, no-store, max-age=0, must-revalidate
    Content-Type: application/json;charset=UTF-8
    Date: Thu, 19 May 2016 13:19:06 GMT
    Expires: 0
    Pragma: no-cache
    Server: Apache-Coyote/1.1
    Set-Cookie: JSESSIONID=BCD37413CCC45CC6EEFA66002F93849E; Path=/; HttpOnly
    Transfer-Encoding: chunked
    X-Content-Type-Options: nosniff
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    
    {
        "error": "Forbidden",
        "message": "No message available",
        "path": "/oauth/token",
        "status": 403,
        "timestamp": 1463663946322
    }
    ```

    NOTE: In this case, the response is JSON.

**Comment by mraible** [comment]
Here's the code that I'm using to get an initial access token:

https://github.com/stormpath/stormpath-sdk-java/blob/569-oauth-client-credentials-grant/impl/src/main/java/com/stormpath/sdk/impl/oauth/DefaultOAuthClientCredentialsGrantRequestAuthenticator.java#L119

This seems to get the token successfully. However, when I parse the token as a JWT, I get different information from it. Here's what I'm using to parse the JWT:

https://github.com/stormpath/stormpath-sdk-java/blob/569-oauth-client-credentials-grant/impl/src/main/java/com/stormpath/sdk/impl/oauth/DefaultOAuthClientCredentialsGrantRequestAuthenticator.java#L85

In the first case, `tokenResponse.getExpiresIn()` returns 3600. However, when I feed this token into the following:

```java
Claims claims = Jwts.parser()
    .setSigningKey(apiKeySecret.getBytes("UTF-8"))
    .parseClaimsJws(credentialsGrantRequest.getJwt()).getBody();
```

Calling `claims.getExpiration().getTime()` returns 1464020035000. If I inspect to see what `claims.getExpiration()` is, it's one hour from the current time. 

```
"expires_in" -> "Mon May 23 10:16:29 MDT 2016"
```

Does this mean after parsing the JWT that I need to subtract the current time from the expiration date in the JWT?

**Comment by mraible** [comment]
The following seems to work for converting the JWT's date to one that's seconds from now:

```java
Date now = new Date();
Date expirationDate = claims.getExpiration();
long timeToExpiration = expirationDate.getTime() - now.getTime();
TimeUnit timeUnit = TimeUnit.SECONDS;
timeToExpiration = timeUnit.convert(timeToExpiration, TimeUnit.MILLISECONDS);
```

**Comment by mraible** [comment]
@dogeared I designed [DefaultClientCredentialsAuthenticationRequestFactory](https://github.com/stormpath/stormpath-sdk-java/blob/569-oauth-client-credentials-grant/extensions/servlet/src/main/java/com/stormpath/sdk/servlet/filter/oauth/DefaultClientCredentialsAuthenticationRequestFactory.java) to look for `apiKeyId` and `apiKeySecret` parameters in the URL. Should I change this to use the Authentication header?

Regardless, when I change the initial request to be the following, I get an invalid_client error. 

```
http -v -f POST localhost:8080/oauth/token \
>     Origin:http://localhost:8080 \
>     grant_type=client_credentials \
>     apiKeyId=123 \
>     apiKeySecret=456

POST /oauth/token HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 125
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: localhost:8080
Origin: http://localhost:8080
User-Agent: HTTPie/0.9.3

grant_type=client_credentials&apiKeyId=123&apiKeySecret=456

HTTP/1.1 400 Bad Request
Cache-Control: no-store
Connection: close
Content-Length: 130
Content-Type: application/json;charset=UTF-8
Date: Mon, 23 May 2016 16:04:33 GMT
Pragma: no-cache
Server: Apache-Coyote/1.1

{
    "error": "invalid_request",
    "error_description": "Unable to authenticate client credentials request: ",
    "error_uri": "invalid_client"
}
```

**Comment by mraible** [comment]
Made it a little further. It seems the following line in `BasicApiAuthenticator` is returning a null ApiKey:

```
ApiKey apiKey = application.getApiKey(id, new DefaultApiKeyOptions().withAccount());
```

**Comment by dogeared** [comment]
Yes @mraible. Per https://tools.ietf.org/html/rfc6749#section-4.4, authentication should occur based on the `Authorization` header. Only the `grant_type=client_credentials` is passed as a query param.

**Comment by mraible** [comment]
After discussions with @dogeared, it seems this PR is currently doing it wrong by requiring the user to pass in the apiKeyId and apiKeySecret. If I remove these values, how should I get them in `DefaultOAuthClientCredentialsGrandRequestAuthenticator`? Should I reverse-engineer the Authorization header to get the values or just pass the value along for the Basic Auth request?

If I remove them, how should I set them in a test? Here's a test in `ApplicationIT.groovy` that currently passes when using apiKeyId and apiKeySecret:

```java
@Test
void testAttemptAuthenticationWithClientCredentials() {
    def app = createTempApp()
    def account = createTestAccount(app)
    def apiKey = account.createApiKey()
    String apiKeyId = apiKey.id
    String apiKeySecret = apiKey.secret

    OAuthClientCredentialsGrantRequestAuthentication grantRequest = OAuthRequests.OAUTH_CLIENT_CREDENTIALS_GRANT_REQUEST.builder()
            .setApiKeyId(apiKeyId)
            .setApiKeySecret(apiKeySecret)
            .build()

    def grantResult = Authenticators.OAUTH_CLIENT_CREDENTIALS_GRANT_REQUEST_AUTHENTICATOR
            .forApplication(app)
            .authenticate(grantRequest)

    // Authenticate token against Stormpath using client credentials token
    grantRequest = OAuthRequests.OAUTH_CLIENT_CREDENTIALS_GRANT_REQUEST.builder()
            .setJwt(grantResult.getAccessTokenString())
            .build()

    assertNotNull Authenticators.OAUTH_CLIENT_CREDENTIALS_GRANT_REQUEST_AUTHENTICATOR
            .forApplication(app).withLocalValidation().authenticate(grantRequest)
}
```

**Comment by mraible** [comment]
@dogeared This is ready for review again, pending CI passing.

**Pull request merged**
