### PR TITLE
Refactor IdSiteResultController to clean up duplicate code for access token exchange

### LINKED ISSUE #744: Refactor client_credentials grant type to use backend
Now that there's backend support for client_credentials, we can refactor our code to use it.

### PR DESCRIPTION
**Pull request by jarias**
Fixes #744 (re-open)

### CODE REVIEW

**Comment by lhazlewood** [comment]
@jarias does this need to be merged w/ master before we should review it?

**Comment by jarias** [comment]
@lhazlewood I don't think so

**Comment by dogeared** [comment]
heh. I merged in master just to be safe. The build failed before, but maybe nothing to do with the code. All passed now...

**Comment by jarias** [comment]
Creating a new PR out of idsite_in_servlet

**Pull request closed without merging**
