### PR TITLE
Spring MVC: Add support for returning 401 and 404 errors as JSON

### LINKED ISSUE #706: Spring Security is returning HTML instead of JSON under certain circumstances
Steps to reproduce:

Start the `spring-security-webmvc` example.

execute: `http -v localhost:8080/restricted`

You will get a response like:

```
GET /restricted HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8080
User-Agent: HTTPie/0.9.3



HTTP/1.1 403 Forbidden
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Language: en
Content-Length: 1030
Content-Type: text/html;charset=utf-8
Date: Tue, 14 Jun 2016 20:55:36 GMT
Expires: 0
Pragma: no-cache
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=D63ACC4D45D447C1CD48652EC8CCB686; Path=/; HttpOnly
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block

<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.28 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 403 - Access Denied</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>Access Denied</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><hr class="line"><h3>Apache Tomcat/8.0.28</h3></body></html>
```

For the control, test with the `servlet` example.

Hit: `http -v localhost:8080/dashboard`

You will get back:

```
http -v localhost:8080/dashboard
GET /dashboard HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8080
User-Agent: HTTPie/0.9.3



HTTP/1.1 401 Unauthorized
Cache-Control: no-store
Content-Length: 0
Date: Tue, 14 Jun 2016 20:57:55 GMT
Pragma: no-cache
Server: Apache-Coyote/1.1
WWW-Authenticate: Basic realm="My Application"
WWW-Authenticate: Bearer realm="My Application"
```

This is the correct response for a protected JSON response where authentication has failed.

### PR DESCRIPTION
**Pull request by mraible**
Fixes #706.

## To UAT Spring MVC

Start `examples/spring-webmvc` and make the following requests:

1. `curl -v -H "Accept: text/html" http://localhost:8080/missing`
2. `curl -v -H "Accept: application/json" http://localhost:8080/missing`

The first one should result in an HTML response, the second should contain JSON. The message from JSON is a key since i18n is often done client-side when talking to a JSON API.

## To UAT Spring Security

Start `examples/spring-security-webmvc` and make the following requests:

1. `curl -v -H "Accept: text/html" http://localhost:8080/missing`
2. `curl -v -H "Accept: application/json" http://localhost:8080/missing`
3. `curl -v -H "Accept: text/html" http://localhost:8080/restricted`
4. `curl -v -H "Accept: application/json" http://localhost:8080/restricted`

Requests with `text/html` should result in an HTML response. Requests with `application/json` should result in a JSON response.

### CODE REVIEW

**Comment by mraible** [comment]
This PR needs some additional work after merging with master.

**Comment by mraible** [comment]
@dogeared @mrioan @jarias @mzumbadoate This PR is ready for review.

**Comment by lhazlewood** [comment]
@mraible are there TCK tests that exercise this UAT?

I'm doing them manually, but we should have TCK tests for this too.

**Comment by mraible** [comment]
@lhazlewood I'm not sure, but I don't think so.

**Comment by lhazlewood** [comment]
When a server responds with 401, it `MUST` (per the HTTP RFC for [HTTP Authentication](https://tools.ietf.org/html/rfc7235#section-3.1)) set the `WWW-Authenticate` header to explain what means of authentication are supported.  cc @edjiang

**Comment by lhazlewood** [comment]
We should have TCK tests for these UATs as well as verifying the 401 `WWW-Authenticate`.  Back over to you @mraible to add to the TCK.

**Comment by mraible** [comment]
@lhazlewood I [added some tests](https://github.com/stormpath/stormpath-framework-tck/pull/293) to the TCK. Results aren't great. I was able to fix the servlet example [not throwing a 404](https://github.com/stormpath/stormpath-sdk-java/pull/726/commits/7e0961d35afcca7193afdeb4da2db085db3a6ee0), but it looks like there's work to do on the other integrations. 

We'll likely have to write a new servlet to handle return 404 errors as JSON since Tomcat doesn't handle this.

**Comment by lhazlewood** [comment]
@mraible I don't think 404 content payload is defined in our spec - I believe it is 'let the underlying rendering engine (e.g. Tomcat) decide what to do'.  Can you please confirm @dogeared or @mrioan ?

**Comment by edjiang** [comment]
Yeah, I think the idea is any undefined endpoints should probably 404; not sure why a framework would put a different result.

**Comment by dogeared** [comment]
replaced by #820

**Pull request closed without merging**
