### PR TITLE
Refactor /logout to respond only to POSTs and to support JSON requests

### LINKED ISSUE #578: Refactor /logout to respond only to POSTs and to support JSON requests
per the framework spec [here](https://github.com/stormpath/stormpath-framework-spec/blob/master/logout.md).

- We need to change the current behavior that supports GET for logout
- We need to add support for `application/json` requests per the spec

Note: We will need to have messaging around the API change for current users. This issue should be added to the [migration guide](https://github.com/stormpath/stormpath-sdk-java/issues/579)

### PR DESCRIPTION
**Pull request by jarias**
Fixes #578

### CODE REVIEW

**Comment by mraible** [comment]
LGTM 👍

**Comment by dogeared** [comment]
please merge @jarias

**Comment by dogeared** [comment]
depends on #364

**Comment by dogeared** [comment]
Replaced by #616

**Pull request closed without merging**
